FROM golang:$GOLANG_VERSION AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN go build -o /app/$PROJECT

FROM alpine:$ALPINE_VERSION
RUN apk add --no-cache ca-certificates
COPY --from=build /app/$PROJECT /app/$PROJECT
EXPOSE $PORT
ENTRYPOINT ["/app/$PROJECT"]
